name: gaitbase
channels:
  - conda-forge
dependencies:
  - python
  - jupyter
  - pyqt
  - psutil
  - xlrd
  - xlsxwriter
  - xlutils
  - pip
  - pip:
    - flake8
    - pypdf2
    - pytest
    - https://github.com/jjnurminen/liikelaaj/archive/master.zip
    - https://github.com/jjnurminen/ulstools/archive/master.zip
