name: gaitbase
channels:
  - conda-forge
dependencies:
  - python
  - jupyter
  - pyqt
  - psutil
  - textdistance
  - xlrd
  - xlsxwriter
  - xlutils
  - pip
  - flake8
  - pypdf2
  - pytest
  - pip:
    - https://github.com/NCH-Motion-Laboratory/configdot/archive/master.zip
    - https://github.com/NCH-Motion-Laboratory/ulstools/archive/master.zip
    - https://github.com/NCH-Motion-Laboratory/gaitbase/archive/master.zip
